<?php

namespace DidUngar\BlogBundle\Entity;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategRepository extends \Doctrine\ORM\EntityRepository
{
}
